package se.bth.swatkats.letstalk.gui;

import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import se.bth.swatkats.letstalk.connection.GuiHandler;
import se.bth.swatkats.letstalk.user.User;

/**
 * This class provides the window which lets the users to add and delete others
 * users from the local address book.
 * 
 * @author Sokratis Papadopoulos and David Alarcon Prada.
 */
public class AddDeleteUser extends javax.swing.JFrame {

    private ArrayList<User> globalUsers;
    
    /**
     * Creates new form AddDeleteUser.
     */
    public AddDeleteUser() {
        initComponents();
        myInitComponents();
    }
    
    /**
     * Provides modifications written by us.
     */
    private void myInitComponents(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("img/iconHead.png")));
        selectUserToAdd.setModel(new javax.swing.DefaultComboBoxModel(putNames()));
        selectUserToDelete.setModel(new javax.swing.DefaultComboBoxModel(putUsersToDelete()));
        
        this.addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent event){
                GuiHandler.getInstance().getGui().updateContacts();
                setVisible(false);
            }
        });
    }
    /**
     * This method gets the users from the local address book.
     * 
     * @return temp - This String[] contains all the users of local address book.
     */
    private String[] putUsersToDelete(){
        String[] temp = new String[GuiHandler.getInstance().searchLocalUsers(GuiHandler.getInstance().getUser().getId(), "").size()];
        int pos=0;
        for(User u: GuiHandler.getInstance().searchLocalUsers(GuiHandler.getInstance().getUser().getId(), "")){
            temp[pos++] = u.getUsername() + " - " + u.getEmail();
        }
        return temp;
    }
    
    /**
     * This method gets the users from the database.
     * 
     * @return temp - This String[] contains all the users of the system.
     */
    private String[] putNames(){
        globalUsers = GuiHandler.getInstance().searchGlobalUsers("",GuiHandler.getInstance().getUser().getId());
        String[] temp = new String[globalUsers.size()];
        int pos=0;
        for(User u: globalUsers){
            temp[pos++] = u.getUsername() + " - " + u.getEmail();
        }
        return temp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addDeleteUserIcon = new javax.swing.JLabel();
        addDeleteUserLabel = new javax.swing.JLabel();
        addDeleteUserPanel = new javax.swing.JPanel();
        oldPasswordLabel = new javax.swing.JLabel();
        repeatNewPasswordLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        selectUserToAdd = new javax.swing.JComboBox();
        performAddUserButton = new javax.swing.JButton();
        performDeleteUserButton = new javax.swing.JButton();
        acceptButton = new javax.swing.JButton();
        selectUserToDelete = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(247, 247, 247));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(247, 247, 247));

        addDeleteUserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/se/bth/swatkats/letstalk/gui/img/usertype.png"))); // NOI18N

        addDeleteUserLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addDeleteUserLabel.setText("Add / Delete User");

        addDeleteUserPanel.setBackground(new java.awt.Color(237, 237, 255));
        addDeleteUserPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        oldPasswordLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/se/bth/swatkats/letstalk/gui/img/addUser.png"))); // NOI18N
        oldPasswordLabel.setText("add user");

        repeatNewPasswordLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/se/bth/swatkats/letstalk/gui/img/deleteUser.png"))); // NOI18N
        repeatNewPasswordLabel.setText("delete user");

        cancelButton.setText("Close");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        performAddUserButton.setText("Perform");
        performAddUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performAddUserButtonActionPerformed(evt);
            }
        });

        performDeleteUserButton.setText("Perform");
        performDeleteUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performDeleteUserButtonActionPerformed(evt);
            }
        });

        acceptButton.setText("Okay");
        acceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addDeleteUserPanelLayout = new javax.swing.GroupLayout(addDeleteUserPanel);
        addDeleteUserPanel.setLayout(addDeleteUserPanelLayout);
        addDeleteUserPanelLayout.setHorizontalGroup(
            addDeleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDeleteUserPanelLayout.createSequentialGroup()
                .addGroup(addDeleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addDeleteUserPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(addDeleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(repeatNewPasswordLabel)
                            .addComponent(oldPasswordLabel))
                        .addGap(18, 18, 18)
                        .addGroup(addDeleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectUserToAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectUserToDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(addDeleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(performDeleteUserButton)
                            .addComponent(performAddUserButton)))
                    .addGroup(addDeleteUserPanelLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(acceptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addDeleteUserPanelLayout.setVerticalGroup(
            addDeleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDeleteUserPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(addDeleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oldPasswordLabel)
                    .addComponent(selectUserToAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(performAddUserButton))
                .addGap(27, 27, 27)
                .addGroup(addDeleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(repeatNewPasswordLabel)
                    .addComponent(performDeleteUserButton)
                    .addComponent(selectUserToDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addDeleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(acceptButton))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addDeleteUserIcon)
                .addGap(33, 33, 33)
                .addComponent(addDeleteUserLabel)
                .addGap(112, 112, 112))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addDeleteUserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addDeleteUserIcon, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(addDeleteUserLabel)
                        .addGap(29, 29, 29)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addDeleteUserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * When the user presses this button, the window is closed.
     * 
     * @param evt - event.
     */
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

   
    /**
     * When the user presses this button, the action (add user) is 
     * performed.
     * 
     * @param evt - event.
     */
    private void performAddUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performAddUserButtonActionPerformed
        //showMessageDialog(null,selectUserToAdd.getSelectedItem().toString());
        String selectedUserName = selectUserToAdd.getSelectedItem().toString();
        for(User u : globalUsers){
            if (selectedUserName.equals(u.getUsername() + " - " +u.getEmail())){
                GuiHandler.getInstance().addLocalUser(GuiHandler.getInstance().getUser().getId(), u.getId());
                break;
            }
        }
    }//GEN-LAST:event_performAddUserButtonActionPerformed
    
    /**
     * When the user presess this button, the action (delete user) is 
     * performed.
     * 
     * @param evt  - event.
     */
    private void performDeleteUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performDeleteUserButtonActionPerformed
        //showMessageDialog(null,selectUserToDelete.getSelectedItem().toString());
        String selectedUserName = selectUserToDelete.getSelectedItem().toString();
        for(User u : GuiHandler.getInstance().searchLocalUsers(GuiHandler.getInstance().getUser().getId(), "")){
            if (selectedUserName.equals(u.getUsername() + " - " + u.getEmail())){
//                System.out.println("DELETION: user "+ GuiHandler.getInstance().getUser().getId() + " will delete " + u.getId());
                GuiHandler.getInstance().deleteUserFromLocalBook(GuiHandler.getInstance().getUser().getId(), u.getId());
                break;
            }
        }
    }//GEN-LAST:event_performDeleteUserButtonActionPerformed
    /**
     * When the user presess this button, the action is performed (update 
     * local address book).
     * 
     * @param evt - event.
     */
    private void acceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptButtonActionPerformed
        // TODO add your handling code here:
        GuiHandler.getInstance().getGui().updateContacts();
        this.setVisible(false);

    }//GEN-LAST:event_acceptButtonActionPerformed

    /**
     * Main method which starts the class.
     * 
     * @param args the command line arguments.
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDeleteUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDeleteUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDeleteUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDeleteUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDeleteUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JLabel addDeleteUserIcon;
    private javax.swing.JLabel addDeleteUserLabel;
    private javax.swing.JPanel addDeleteUserPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel oldPasswordLabel;
    private javax.swing.JButton performAddUserButton;
    private javax.swing.JButton performDeleteUserButton;
    private javax.swing.JLabel repeatNewPasswordLabel;
    private javax.swing.JComboBox selectUserToAdd;
    private javax.swing.JComboBox selectUserToDelete;
    // End of variables declaration//GEN-END:variables
}
