package se.bth.swatkats.letstalk.gui;

import java.awt.Toolkit;

import static javax.swing.JOptionPane.showMessageDialog;
import se.bth.swatkats.letstalk.connection.GuiHandler;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.InputMap;
import javax.swing.KeyStroke;
/**
 * This class provides the window which lets the users to change his/her
 * password.
 * 
 * @author Sokratis Papadopoulos and David Alarcon.
 */
public class ChangePassword extends javax.swing.JFrame {

    /**
     * Creates new form ChangePassword.
     */
    public ChangePassword() {
        initComponents();
        myInitComponents();
    }
    
    /**
     * Provides modifications written by us.
     */
    private void myInitComponents(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("img/iconHead.png")));
        InputMap map = new InputMap();
        map.put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER,0,true), "released");
        performNewPass.setInputMap(0, map);
        closeButton.setInputMap(0, map);
        
        this.addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent event){
                setVisible(false);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wholeChangePasswordPanel = new javax.swing.JPanel();
        changePasswordLabel = new javax.swing.JLabel();
        changePasswordImage = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        oldPasswordLabel = new javax.swing.JLabel();
        newPasswordLabel = new javax.swing.JLabel();
        repeatNewPasswordLabel = new javax.swing.JLabel();
        oldPasswordInput = new javax.swing.JPasswordField();
        newPasswordInput = new javax.swing.JPasswordField();
        repeatNewPasswordInput = new javax.swing.JPasswordField();
        closeButton = new javax.swing.JButton();
        performNewPass = new javax.swing.JButton();

        setBackground(new java.awt.Color(247, 247, 247));
        setResizable(false);

        wholeChangePasswordPanel.setBackground(new java.awt.Color(247, 247, 247));

        changePasswordLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        changePasswordLabel.setText("Change Password");

        changePasswordImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/se/bth/swatkats/letstalk/gui/img/changePassword.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(237, 237, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        oldPasswordLabel.setText("old password");

        newPasswordLabel.setText("new password");

        repeatNewPasswordLabel.setText("repeat new password");

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        closeButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                closeButtonKeyReleased(evt);
            }
        });

        performNewPass.setText("Perform");
        performNewPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performNewPassActionPerformed(evt);
            }
        });
        performNewPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                performNewPassKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(repeatNewPasswordLabel)
                            .addComponent(oldPasswordLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addComponent(newPasswordLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(performNewPass))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newPasswordInput)
                    .addComponent(repeatNewPasswordInput)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(oldPasswordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(closeButton)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(oldPasswordLabel)
                            .addComponent(oldPasswordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(newPasswordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(newPasswordLabel)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(repeatNewPasswordLabel)
                    .addComponent(repeatNewPasswordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeButton)
                    .addComponent(performNewPass))
                .addContainerGap())
        );

        javax.swing.GroupLayout wholeChangePasswordPanelLayout = new javax.swing.GroupLayout(wholeChangePasswordPanel);
        wholeChangePasswordPanel.setLayout(wholeChangePasswordPanelLayout);
        wholeChangePasswordPanelLayout.setHorizontalGroup(
            wholeChangePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wholeChangePasswordPanelLayout.createSequentialGroup()
                .addGroup(wholeChangePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wholeChangePasswordPanelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(changePasswordImage)
                        .addGap(36, 36, 36)
                        .addComponent(changePasswordLabel))
                    .addGroup(wholeChangePasswordPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        wholeChangePasswordPanelLayout.setVerticalGroup(
            wholeChangePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, wholeChangePasswordPanelLayout.createSequentialGroup()
                .addGroup(wholeChangePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wholeChangePasswordPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(changePasswordLabel)
                        .addGap(25, 25, 25))
                    .addGroup(wholeChangePasswordPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(changePasswordImage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wholeChangePasswordPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(wholeChangePasswordPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
   
    /**
     * When the user presses this button, the window is closed.
     * 
     * @param evt - event.
     */
    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_closeButtonActionPerformed

    /**
     * When the user presses this button, the action (change password) is 
     * performed.
     * 
     * @param evt - event.
     */
    private void performNewPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performNewPassActionPerformed
        String oldPass = this.oldPasswordInput.getText();
        String newPass = this.newPasswordInput.getText();
        String repeatNewPass = this.repeatNewPasswordInput.getText();
        
        if(newPass.equals(repeatNewPass)){ //if the new password and repeated new password are same
            
            switch(GuiHandler.getInstance().changeUserPassword(GuiHandler.getInstance().getUser().getId(), GuiHandler.getInstance().getUser().getUsername(), oldPass, newPass)){
                case 0:
                    showMessageDialog(null, "There was a problem with our server. \n"
                    + "Please contact administrator.");
                    this.setVisible(false);
                    break;
                case 1:
                    showMessageDialog(null, "Password successfully changed.");
                    this.setVisible(false);
                    break;
                case -1:
                    showMessageDialog(null, "The old password you provided is wrong. \n "
                            + "Please try again.");
                    this.oldPasswordInput.setText("");
                    this.newPasswordInput.setText("");
                    this.repeatNewPasswordInput.setText("");
                    break;
                default:
                    showMessageDialog(null, "There was an unexpected problem with our server. \n"
                    + "Please contact administrator.");    
                    this.setVisible(false);
            }     
        } else {
            showMessageDialog(null,"New password doesnt match. Be careful and try again!");
            this.newPasswordInput.setText("");
            this.repeatNewPasswordInput.setText("");
        }
    }//GEN-LAST:event_performNewPassActionPerformed

    /**
     * This method lets the user employment the enter button to perform the password's change.
     * 
     * @param evt - event.
     */
    private void performNewPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_performNewPassKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            performNewPassActionPerformed(null);
        }
    }//GEN-LAST:event_performNewPassKeyReleased

    /**
     * This method lets the user employment the enter button to close the window.
     * 
     * @param evt - event.
     */
    private void closeButtonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_closeButtonKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            closeButtonActionPerformed(null);
        }
    }//GEN-LAST:event_closeButtonKeyReleased

    /**
     * Main method which starts the class.
     * 
     * @param args the command line arguments.
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel changePasswordImage;
    private javax.swing.JLabel changePasswordLabel;
    private javax.swing.JButton closeButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField newPasswordInput;
    private javax.swing.JLabel newPasswordLabel;
    private javax.swing.JPasswordField oldPasswordInput;
    private javax.swing.JLabel oldPasswordLabel;
    private javax.swing.JButton performNewPass;
    private javax.swing.JPasswordField repeatNewPasswordInput;
    private javax.swing.JLabel repeatNewPasswordLabel;
    private javax.swing.JPanel wholeChangePasswordPanel;
    // End of variables declaration//GEN-END:variables
}
