package se.bth.swatkats.letstalk.gui;

import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import static javax.swing.JOptionPane.showMessageDialog;
import se.bth.swatkats.letstalk.connection.GuiHandler;
import se.bth.swatkats.letstalk.user.User;

/**
 * This class provides the window which lets a user start a new conversation
 * with other user.
 * 
 * @author Sokratis Papadopoulos and David Alarcon Prada.
 */
public class NewConversation extends javax.swing.JFrame {
    private ArrayList<User> localUsers;

   
    /**
     * Creates new form NewConversation
     */
    public NewConversation() {
        initComponents();
        myInitComponents();
    }
    
    /**
     * Provides modifications written by us.
     */
    private void myInitComponents(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("img/iconHead.png")));
        selectUserToAdd.setModel(new javax.swing.DefaultComboBoxModel(putNames()));
        this.addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent event){
                GuiHandler.getInstance().getGui().updateConversations();
                setVisible(false);
            }
        });
    }    
    
    /**
     * This method gets the users from the database.
     * 
     * @return temp - This String[] contains all the users of the system.
     */
    private String[] putNames(){
        localUsers = GuiHandler.getInstance().searchLocalUsers(GuiHandler.getInstance().getUser().getId(), "");
        
        String[] temp = new String[localUsers.size()];
        int pos=0;
        for(User u: localUsers)
            temp[pos++] = u.getUsername() + " - " + u.getEmail();
        
        return temp;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newConversationPanel = new javax.swing.JPanel();
        addDeleteUserIcon = new javax.swing.JLabel();
        createNewConversationLabel = new javax.swing.JLabel();
        selectUserPanel = new javax.swing.JPanel();
        selectUserLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        selectUserToAdd = new javax.swing.JComboBox();
        createConversationButton = new javax.swing.JButton();
        groupConversationBox = new javax.swing.JCheckBox();
        groupNameText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        newConversationPanel.setBackground(new java.awt.Color(247, 247, 247));

        addDeleteUserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/se/bth/swatkats/letstalk/gui/img/usertype.png"))); // NOI18N

        createNewConversationLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        createNewConversationLabel.setText("Create new Conversation");

        selectUserPanel.setBackground(new java.awt.Color(237, 237, 255));
        selectUserPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        selectUserLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/se/bth/swatkats/letstalk/gui/img/addUser.png"))); // NOI18N
        selectUserLabel.setText("Select user");

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        selectUserToAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectUserToAddActionPerformed(evt);
            }
        });

        createConversationButton.setText("Create");
        createConversationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createConversationButtonActionPerformed(evt);
            }
        });

        groupConversationBox.setText("Group Conversation");
        groupConversationBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupConversationBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout selectUserPanelLayout = new javax.swing.GroupLayout(selectUserPanel);
        selectUserPanel.setLayout(selectUserPanelLayout);
        selectUserPanelLayout.setHorizontalGroup(
            selectUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, selectUserPanelLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(selectUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(groupConversationBox)
                    .addGroup(selectUserPanelLayout.createSequentialGroup()
                        .addGroup(selectUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, selectUserPanelLayout.createSequentialGroup()
                                .addComponent(selectUserLabel)
                                .addGap(41, 41, 41))
                            .addComponent(createConversationButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(selectUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(selectUserPanelLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(selectUserPanelLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(selectUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(groupNameText)
                                    .addComponent(selectUserToAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(65, 65, 65))
        );
        selectUserPanelLayout.setVerticalGroup(
            selectUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectUserPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(selectUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectUserLabel)
                    .addComponent(selectUserToAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(selectUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(groupConversationBox)
                    .addComponent(groupNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(selectUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createConversationButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout newConversationPanelLayout = new javax.swing.GroupLayout(newConversationPanel);
        newConversationPanel.setLayout(newConversationPanelLayout);
        newConversationPanelLayout.setHorizontalGroup(
            newConversationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newConversationPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addDeleteUserIcon)
                .addGap(33, 33, 33)
                .addComponent(createNewConversationLabel)
                .addGap(112, 112, 112))
            .addGroup(newConversationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectUserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        newConversationPanelLayout.setVerticalGroup(
            newConversationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newConversationPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(newConversationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addDeleteUserIcon, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newConversationPanelLayout.createSequentialGroup()
                        .addComponent(createNewConversationLabel)
                        .addGap(29, 29, 29)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectUserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newConversationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(newConversationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This method creates a new conversation when the user presses the button
     * (create).
     * 
     * @param evt - event.
     */
    private void createConversationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createConversationButtonActionPerformed
               
        System.out.println("createConversationButton PRESSED!!!");
        String selectedUserName = selectUserToAdd.getSelectedItem().toString();
        
        
        int chat_type;
        String groupName = "";
        boolean happened = false;
        if(groupConversationBox.isSelected()){
            System.out.println("we know its a group chat");
            chat_type = 0;
            groupName = groupNameText.getText();
            if(groupName.equals(""))
                showMessageDialog(null, "Please provide a group name!");
            else{
                System.out.println("Creating a new Group Chat from userID: " + GuiHandler.getInstance().getUser().getId());
                System.out.println(GuiHandler.getInstance().createConversation(GuiHandler.getInstance().getUser().getId(), -10, chat_type,groupName)); //add last parameter groupName
                happened = true;
            }
        } else{
            chat_type = 1;
            for(User u : localUsers){
                if (selectedUserName.equals(u.getUsername() + " - " +u.getEmail())){
                    System.out.println(GuiHandler.getInstance().createConversation(GuiHandler.getInstance().getUser().getId(), u.getId(), chat_type,groupName)); //add last parameter groupName   
                    happened = true;
                    break;
                }
            }
        }
        
        if(happened){
            GuiHandler.getInstance().getGui().updateConversations();
            this.setVisible(false);
        }
    }//GEN-LAST:event_createConversationButtonActionPerformed

    /**
     * When the user presses this button, the window is closed.
     * 
     * @param evt - event.
     */
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * When the user presses this button, a user of the local address book
     * is selected because the actual user wants to create a new conversation 
     * with him/her.
     * 
     * @param evt - event.
     */
    private void selectUserToAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectUserToAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectUserToAddActionPerformed

    /**
     * When the user selects this checkbox, it will be create a new
     * group conversation.
     * 
     * @param evt - event.
     */
    private void groupConversationBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupConversationBoxActionPerformed
        //showMessageDialog(null, "Please provide group conversation name");
    }//GEN-LAST:event_groupConversationBoxActionPerformed

     /**
     * Main method which starts the class.
     * 
     * @param args the command line arguments.
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewConversation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewConversation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewConversation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewConversation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewConversation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addDeleteUserIcon;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton createConversationButton;
    private javax.swing.JLabel createNewConversationLabel;
    private javax.swing.JCheckBox groupConversationBox;
    private javax.swing.JTextField groupNameText;
    private javax.swing.JPanel newConversationPanel;
    private javax.swing.JLabel selectUserLabel;
    private javax.swing.JPanel selectUserPanel;
    private javax.swing.JComboBox selectUserToAdd;
    // End of variables declaration//GEN-END:variables
}
